sonar.projectKey=smart-waste-backend
sonar.projectName=Smart Waste Backend
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
